apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: balasiq
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/amrilsyaifa/homelab-iac.git
    targetRevision: main
    path: kubernetes/apps/balasiq

  destination:
    server: https://kubernetes.default.svc
    namespace: balasiq

  syncPolicy:
    syncOptions:
      - CreateNamespace=false