# secret.example.yaml

apiVersion: v1
kind: Secret

metadata:
  name: balasiq-postgres-secret
  namespace: balasiq

type: Opaque

stringData:
  POSTGRES_DB: "balasiq"
  POSTGRES_USER: "balasiq_owner"
  POSTGRES_PASSWORD: "CHANGE_ME"

  BALASIQ_APP_USER: "balasiq_app"
  BALASIQ_APP_PASSWORD: "CHANGE_ME"