apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: redis
  namespace: balasiq

spec:
  serviceName: redis
  replicas: 1

  selector:
    matchLabels:
      app: balasiq-redis

  template:
    metadata:
      labels:
        app: balasiq-redis

    spec:
      containers:
        - name: redis
          image: redis:8-alpine

          command:
            - redis-server
            - --appendonly
            - "yes"
            - --maxmemory
            - "512mb"
            - --maxmemory-policy
            - noeviction

          ports:
            - name: redis
              containerPort: 6379

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "640Mi"

          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 2
            failureThreshold: 30

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: redis-data
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: redis-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: local-path

        resources:
          requests:
            storage: 2Gi