apiVersion: v1
kind: ConfigMap

metadata:
  name: balasiq-backend-config
  namespace: balasiq

data:
  APP_PUBLIC_URL: "https://app.home.arpa"
  APP_VERSION: "0.1.0"

  AUTH_COOKIE_SECURE: "true"
  AUTH_COOKIE_SAME_SITE: "None"
  TRUST_PROXY: "true"
  AUTH_SESSION_TTL_DAYS: "30"

  HOST: "0.0.0.0"
  PORT: "4000"
  LOG_LEVEL: "info"

  REDIS_URL: "redis://redis:6379"

  STORAGE_ROOT: "/workspace/.data/objects"