apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: balasiq-backend-data
  namespace: balasiq

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 5Gi