apiVersion: v1
kind: Secret

metadata:
  name: balasiq-backend-secret
  namespace: balasiq

type: Opaque

stringData:
  DATABASE_URL: "postgresql://balasiq_app:CHANGE_ME@postgres:5432/balasiq"
  DATABASE_MIGRATION_URL: "postgresql://balasiq_owner:CHANGE_ME@postgres:5432/balasiq"