apiVersion: v1
kind: ConfigMap

metadata:
  name: balasiq-postgres-init
  namespace: balasiq

data:
  init-role.sql: |
    SELECT format(
      'CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS',
      :'app_user',
      :'app_password'
    )
    WHERE NOT EXISTS (
      SELECT 1
      FROM pg_catalog.pg_roles
      WHERE rolname = :'app_user'
    )
    \gexec

    SELECT format(
      'ALTER ROLE %I PASSWORD %L',
      :'app_user',
      :'app_password'
    )
    \gexec

    SELECT format(
      'GRANT CONNECT ON DATABASE %I TO %I',
      :'db_name',
      :'app_user'
    )
    \gexec